# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# Website info
name: 'Thomas Alexandre'
description: "Emerging engineering and business leader"

# Author's info
author: 'Thomas Alexandre'
#bio: '"Faith, Love and Legacy - the three ideals I strive for."'
#location: 'Ancaster, Ontario, Canada'
linkedin: 'https://www.linkedin.com/in/thomasgalexandre/'
short_linkedin: 'linkedin.com/in/thomasgalexandre/'
url: 'http://thomasgalexandre.com/'
short_url: 'thomasgalexandre.com/'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
image: 'assets/images/about.jpg'

#Analytics
google_analytics: UA-93794806-1
#disqus: username

# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: tgalexandre
repo: tgalexandre.github.io
branch: master
relative_source: ../tgalexandre.github.io/
destination: ../pages/
production_url:  https://tgalexandre.github.io/
source_url:      https://github.com/tgalexandre/tgalexandre.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
